### PR TITLE
Modified path names for compatibility with windows

### PR DESCRIPTION
**Pull request by bdmccord**
Hi Guys, I am part of the SER-401 capstone team who is to develop the game component of SIMOC.  I pulled your code but had some trouble getting it working in windows so I made a few minor changes to some of the path's in the AgentModel/ABM/model.py file to get it working.  I am not sure if we will be committing to your repo during the development or not right now, so feel free to reject this request, I just thought it might be helpful.  Also, looks really cool!

### CODE REVIEW

**Comment by tacox5** [comment]
Hey, I'm Tyler and I've been working on the modeling SIMOC in this repo. I appreciate the fix! I've just been developing this locally the most part and forgot about those file paths. I'm not sure about if you'll be committing to this repo or not, but for now we've mostly just been messing around with preliminary models to begin to work out the backend. I'm sure that'll be more clear as you guys get further into development. Again, thanks for the fix!

**Comment by bdmccord** [comment]
Hey! Sorry I missed your response.  Nice to meet you.  I did actually have a question for you.  I was checking out your tensorflow example, although it is not really in the scope of our task, I was just curious since my primary job at work is using neural networks to do computer vision.  I was wondering why you picked a classification task for your model.  It appears as though the outputs are not mutually independent, for instance a 2 is much more related to a 3 then to an 8.  Also, I am not sure but it appears as though you do not have enough outputs to perform a classification task.  Since you have two class categories, one with around 10 classes and another with about 100, I believe your output shape should be 2 x 100.   This 2x100 matrix output should represent a probability distribution for each class, alternatively you could split your outputs so that you have one 1x10 vector output and another 1x100.

**Comment by tacox5** [comment]
Hey! That's a good question and the answer basically is that I don't have much practical experience working with neural networks just yet. In the beginning of the project, we were testing out how different models might function and I was trying to put together a simple neural net to test what a predictive model might look like, but as you've probably already seen it has its problems. For the time being, we've put aside the neural net model and started working more on the agent model. I still am interested in working with neural networks in certain areas of the project , so it might be nice to talk to you about how to better implement them in the future since you've worked with them quite a bit! In the meantime, I think I might look into a couple of those suggestions you made and try to apply those to the existing model. Thanks!

**Comment by bdmccord** [comment]
No problem!  About 2 years ago I barely knew what neural network were, it
was only chance that I got assigned to work on them at my job.  When I
first started I had know idea what I was doing, they had me take a coursera
course in machine learning which was really helpful.  I'd be happy to help
out as best I can, I am by no means an expert, but I have messed around
with them enough that I should probably have at least some idea of what I
am doing by now.

**Comment by tacox5** [comment]
I appreciate that! I could definitely use the help. I think I might check out that coursera course you mentioned first and see if I can get a better sense for it.

**Pull request merged**
